# Generated by Django 5.1 on 2024-08-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership_class',
            field=models.CharField(choices=[('Milerites', 'Milerites'), ('Missionaries', 'Missionaries'), ('Patriachs', 'Patriachs'), ('Disciples', 'Disciples'), ('Soul Winners', 'Soul Winners'), ('Reminats', 'Reminats'), ('Pioneers', 'Pioneers'), ('Adventurers', 'Adventurers'), ('Baptismal', 'Baptismal')], default='', max_length=20),
        ),
    ]
