# Generated by Django 5.1 on 2024-08-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_membership_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='level_of_study',
            field=models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('Alumi', 'Alumi')], default='', max_length=100),
        ),
    ]
